### ISSUE TITLE
Support download video with https://jable.tv

### ISSUE THREAD

**Issue by extrem23** [684102/PornDownloader#30]
**Is your feature request related to a problem? Please describe.**
Possible to support Download Video with this site? 
It's a great site with JAV and it's free for all content streaming but not available for download

**Describe the solution you'd like**
"Download Video" feature please

**Comment by 684102** [comment]
### External extension for download HDS and HLS fragmented videos.
Because PornDownloader do not support to download fragmented videos, therefore you can check another extension of me, named as [HDS-HLS-Video-Downloader](https://github.com/684102/HDS-HLS-Video-Downloader/issues/3#issuecomment-693213227).
