### ISSUE TITLE
Search video on other sites and recommended sites

### ISSUE THREAD

**Issue by Lucas559-noob** [684102/PornDownloader#31]
Some Japanese videos are uploaded to pornhub and among other sites, but to see more recent videos, they are usually released on Japanese sites, but searching there are several sites (in some the video does not have audio, or is limited for 2 minutes by not have paid for a subscription), so somehow a good site is recommended to watch without having these blocks or make like pornhub, a shared premium account
**Describe the solution you'd like**
When you go to a porn site and want to search for something on a website like Japanese, he recommends me a website to watch without problems, this also happens when I'm watching a video and it can be found on another website

**Comment by 684102** [comment]
Hi there.
Because the PornDownloader is more focus to download than streaming, so ... if you want to find a best of JAV website for download without ads, and high-speed download then i can recommend you javbus.com. 

That's site is only for the torrent link, but they have a lot of seeders, that mean you can download a gb within 5-15 minutes. You can select the quality for the video as you like. 

![image](https://user-images.githubusercontent.com/26831148/93543205-2a11d600-f985-11ea-9a8c-ae010e0fa1fe.png)
Use [μTorrent Web](https://web.utorrent.com/index3.html), you can able to streaming online at your browser without download entire files.

**Comment by babasehad** [comment]
> Hi there.
> 
> Because the PornDownloader is more focus to download than streaming, so ... if you want to find a best of JAV website for download without ads, and high-speed download then i can recommend you [javbus.com](//javbus.com). 
> 
> 
> 
> That's site is only for the torrent link, but they have a lot of peers, that mean you can download a gb within 5-15 minutes. and you can select the quality for the video as you like, up to 4K . 
> 
> ![image](https://user-images.githubusercontent.com/26831148/93544036-3eef6900-f987-11ea-891a-89e98ac04700.png)
> 
> 
> 
> 
> 
> > ![image](https://user-images.githubusercontent.com/26831148/93543314-7230f880-f985-11ea-9fb6-958876298de5.png)
> 
> - Use [μTorrent Web](https://web.utorrent.com/index3.html), you can able to streaming online these movie at your browser without download entire files.
